import type { GalleryImage } from "@/lib/types";

export const galleryImages: GalleryImage[] = [
  {
    src: "/images/location/facade-lauthentique.webp",
    alt: "Façade colorée de L’Authentique au Village Artisanal de Sainte-Anne",
    width: 1600,
    height: 1200,
    category: "L’adresse",
    featured: true,
  },
  {
    src: "/images/food/croque-monsieur.webp",
    alt: "Croque-monsieur accompagné de salade servi à L’Authentique",
    width: 1200,
    height: 1600,
    category: "À table",
    featured: true,
  },
  {
    src: "/images/location/accueil-lauthentique.webp",
    alt: "Accueil souriant derrière le comptoir de L’Authentique",
    width: 1200,
    height: 1600,
    category: "L’accueil",
    featured: true,
  },
  {
    src: "/images/location/terrasse-lauthentique.webp",
    alt: "Terrasse colorée de L’Authentique au Village Artisanal",
    width: 1012,
    height: 1800,
    category: "La terrasse",
  },
  {
    src: "/images/food/assiette-a-partager.webp",
    alt: "Assiette généreuse mêlant poissons, pâtes, salade et accompagnements",
    width: 1200,
    height: 1600,
    category: "Cuisine",
  },
  {
    src: "/images/drinks/cocktail-aperol-terrasse.webp",
    alt: "Cocktail Aperol Spritz servi sur la terrasse de L’Authentique",
    width: 1200,
    height: 1600,
    category: "Cocktails",
  },
  {
    src: "/images/location/bar-lauthentique.webp",
    alt: "Intérieur du bar et comptoir de L’Authentique",
    width: 1800,
    height: 1350,
    category: "Le bar",
  },
  {
    src: "/images/food/cassolette-mer.webp",
    alt: "Cassolette de la mer accompagnée de riz et de salade",
    width: 1200,
    height: 1600,
    category: "Saveurs marines",
  },
  {
    src: "/images/drinks/biere-gwada.webp",
    alt: "Bière Gwada servie à L’Authentique",
    width: 1200,
    height: 1600,
    category: "Boissons locales",
  },
  {
    src: "/images/food/assiette-poisson.webp",
    alt: "Assiette de poisson et accompagnements servie à L’Authentique",
    width: 1200,
    height: 1600,
    category: "Le plat du moment",
  },
];
