import type { GalleryImage } from "@/lib/types";

export const galleryImages: GalleryImage[] = [
  {
    src: "/images/real/facade-wide.webp",
    alt: "Façade de L’Authentique au Village Artisanal de Sainte-Anne",
    width: 900,
    height: 600,
    category: "Le village",
    featured: true,
    placeholder: false,
  },
  {
    src: "/images/real/croque-salade.webp",
    alt: "Assiette servie à L’Authentique avec croque et salade",
    width: 900,
    height: 600,
    category: "À table",
    featured: true,
    placeholder: false,
  },
  {
    src: "/images/real/equipe.webp",
    alt: "L’équipe de L’Authentique derrière le comptoir",
    width: 900,
    height: 600,
    category: "L’équipe",
    featured: true,
    placeholder: false,
  },
  {
    src: "/images/real/terrasse.webp",
    alt: "Terrasse colorée de L’Authentique au Village Artisanal",
    width: 900,
    height: 600,
    category: "La terrasse",
    placeholder: false,
  },
  {
    src: "/images/real/paella.webp",
    alt: "Grand plat de riz aux fruits de mer préparé pour un événement",
    width: 900,
    height: 600,
    category: "Cuisine",
    placeholder: false,
  },
  {
    src: "/images/real/bar-night.webp",
    alt: "Comptoir de L’Authentique illuminé en soirée",
    width: 900,
    height: 600,
    category: "Le soir",
    placeholder: false,
  },
  {
    src: "/images/real/cuisine.webp",
    alt: "Préparation en cuisine à L’Authentique",
    width: 900,
    height: 600,
    category: "En cuisine",
    placeholder: false,
  },
  {
    src: "/images/real/facade-close.webp",
    alt: "Entrée de L’Authentique avec sa terrasse colorée",
    width: 900,
    height: 600,
    category: "Sainte-Anne",
    placeholder: false,
  },
  {
    src: "/images/real/facade-night.webp",
    alt: "Façade de L’Authentique éclairée en soirée",
    width: 900,
    height: 600,
    category: "Après la plage",
    placeholder: false,
  },
  {
    src: "/images/real/facade.jpg",
    alt: "Vue générale de L’Authentique au Village Artisanal des Galbas",
    width: 900,
    height: 600,
    category: "Les Galbas",
    placeholder: false,
  },

];
